server:
  servlet:
    session:
      cookie:
        name: KSESSIONID

security:
  oauth2:
    client:
      client-id: web
      client-secret: webpass
      user-authorization-uri: http://localhost:8282/oauth/authorize
      access-token-uri: http://localhost:8282/oauth/token
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
