Server:
  Port:8282
Spring:
  Security:
    user:
      name:
      password:
      roles:ADMIN, USER
Security:
  oauth2:
    client:
      client-id: mobile
      clienr-secret: pin
      access-token-validity-seconds:3600
      authorized-grant-types: refresh_token, authorization_code,password, client_credentials
      scope: READ, WRITE

